### PR TITLE
Updated Chunkutils dependency

### PR DESCRIPTION
**Pull request by Millesant**
Checked in-game and no errors/problems where given

### CODE REVIEW

**Comment by psevdonimux** [comment]
what will it do, and what is the point of it? Personally, I don't see anything other than changing the name of the dependency.

**Comment by psevdonimux** [comment]
won't the message be displayed? or will it affect something else? if I'm right, then there is no point in this as in this check, because it is authentic in itself if the binary corresponds to what is downloaded from installer.sh

**Comment by Millesant** [comment]
I believe that keeping the dependencies up to date can improve performance in some way, but if there is no need you can close the pull request 🙏

**Comment by psevdonimux** [comment]
I do not agree with you in terms of performance, but if we talk about the correctness of checking for this dependency and the output of this message, therefore I accept

**Pull request merged**
